FROM microsoft/dotnet:1.1.2-runtime
WORKDIR /dotnetapp
COPY ./bin/Docker .
ENV ASPNETCORE_URLS http://*:10001
ENV ASPNETCORE_ENVIRONMENT development
ENTRYPOINT dotnet Collectively.Services.Operations.dll